# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlipBit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlipBit
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  target 'FlipBitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlipBitUITests' do
    # Pods for testing
  end

end
